#!/usr/bin/env python3
"""Generate js/books-inline.js from books/*.md.

Only needed for file:// use: a browser blocks fetch and XHR for local files,
so the texts are also shipped as a script that sets window.INKWELL_RAW.
Over http the reader never loads it.

Run after editing any book:
    python3 tools/build_inline.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
BOOKS = ROOT / "books"
OUT = ROOT / "js" / "books-inline.js"

HEADER = """/* books-inline.js - GENERATED by tools/build_inline.py. Do not edit by hand.
 *
 * A copy of every book as a string, so index.html works when opened
 * straight off a disk, where the browser blocks fetch and XHR for local
 * files. The reader injects this file only when it detects a file://
 * origin, so it costs nothing on the deployed site.
 */
window.INKWELL_RAW = %s;
"""


def title_of(text: str) -> str:
    m = re.search(r"^#\s+(.+)$", text, re.M)
    return m.group(1).strip() if m else ""


def main() -> None:
    payload = {}
    for path in sorted(BOOKS.glob("*.md")):
        payload[path.stem] = path.read_text(encoding="utf-8")
    if not payload:
        raise SystemExit("no markdown found in %s" % BOOKS)
    body = json.dumps(payload, ensure_ascii=False, indent=0, sort_keys=True)
    OUT.write_text(HEADER % body, encoding="utf-8")
    print("wrote %s (%d books, %.0f KB)" % (
        OUT.relative_to(ROOT), len(payload), OUT.stat().st_size / 1024))


if __name__ == "__main__":
    main()
